import Head from 'next/head';
import { FC } from 'react';

interface Props {
  title: String;
}

const HtmlHead: FC<Props> = ({ title }) => (
  <Head>
    <title>{title}</title>
    <meta content="Generated by create next app" name="description" />
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <link href="/favicon.png" rel="shortcut icon" />
  </Head>
);

export default HtmlHead;
